apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-app
  namespace: default
spec:
  interval: 5m
  url: https://github.com/surajssd/test-flux
  ref:
    commit: a8e9ee73668c30c652281778808d1d8e14eb7684
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: default
spec:
  interval: 15m
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app
